server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    cache: false

# Настройки Keycloak (если используется)
keycloak:
  realm: diploma-realm
  auth-server-url: http://localhost:8081/
  client-id: admin-cli
  username: admin
  password: admin
  resource: auth-service
  public-client: true
  bearer-only: false
  ssl-required: none
  use-resource-role-mappings: true

# URL для перенаправления после успешной авторизации
app:
  redirect-url: http://localhost:8090/
