server:
  port: 8090

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway-client
            client-secret: secret
            scope: openid
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/diploma-realm
            authorization-uri: http://localhost:8080/realms/diploma-realm/protocol/openid-connect/auth
            token-uri: http://localhost:8080/realms/diploma-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:8080/realms/diploma-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

        - id: frontend-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/frontend/**
          filters:
            - StripPrefix=2

        - id: image-hosting
          uri: http://localhost:8084
          predicates:
            - Path=/api/images/**
          filters:
            - StripPrefix=2
