server:
  port: 8082  # Порт для frontend-service

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # Отключение кеша шаблонов при разработке

  mvc:
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

logging:
  level:
    org.springframework: info

app:
  title: "frontend-service - Gateway for Image Hosting"
  version: "1.0"
