server:
  port: 8084

spring:
  application:
    name: image-hosting

  datasource:
    url: jdbc:postgresql://localhost:5432/images_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true

  devtools:
    restart:
      enabled: true
      additional-paths:
        - target/uploads/images
      exclude:
        - static/**
    livereload:
      enabled: true

upload:
  path: target/uploads/images

logging:
  level:
    org.springframework.web: DEBUG
